### ISSUE TITLE
Overlay not working with non-standard controls I believe.

### ISSUE THREAD

**Issue by Fozz13** [alex47exe/gse_fork#2]
When playing "Thank Goodness You're Here" the experimental overlay does not work. But the exact same settings used with a different game works just fine. I am not a developer so take my opinion with a grain of salt, but I believe it is a problem of the overlay keybind "Shift+Tab" not working with non-standard keybinds with games. "Thank Goodness You're Here" doesn't have a mouse instead using keys for menu navigation. With the original Goldberg this same problem occurred with Celeste with also doesn't use the mouse. I fully understand it is experimental and am not look for a solution, this is just a bug that I have noticed.

**Comment by alex47exe** [comment]
The overlay can be hit and miss, not guaranteed to work with every game. As far as I've noticed, it will work just fine with games using engines like Unreal, Unity, while some new games using proprietary engines might crash when accessing the overlay, or not start at all when overlay is enabled. 

I'll close this for now. You might wanna have a look at this release, it seems to fix overlay issues in some games:
[https://github.com/alex47exe/gse_fork/releases/tag/2024_17_11](https://github.com/alex47exe/gse_fork/releases/tag/2024_17_11)
