### ISSUE TITLE
Missing Interface error

### ISSUE THREAD

**Issue by MrStrangerx** [alex47exe/gse_fork#3]
WWE 2K24 tried your fork but having problem, game shutdown itself with this error, can you help me ?

![image](https://github.com/user-attachments/assets/4c53d034-3dc0-4930-8485-82720877e6bc)

**Comment by alex47exe** [comment]
Seems to have been fixed by @universal963 on @Detanup01's [gbe_fork](https://github.com/Detanup01/gbe_fork), which is now merged into mine as well, so I'll close this now.
