### ISSUE TITLE
Python Missing Dependency: steam[client] Repository Not Found

### ISSUE THREAD

**Issue by Hylith1** [alex47exe/gse_fork#4]
Hello,

I am attempting to build the project using the provided instructions, but I encountered an issue with a missing dependency.

When running the build process, the following error occurs:

```
Running command git clone --filter=blob:none --quiet https://github.com/Sak32009/steam_py_fork.git
  remote: Repository not found.
  fatal: repository 'https://github.com/Sak32009/steam_py_fork.git/' not found
```

It appears that the GitHub repository https://github.com/Sak32009/steam_py_fork.git is no longer accessible. As a result, I am unable to proceed with the build process.

Do you have a fix ?

**Comment by alex47exe** [comment]
Should be fixed now, thanks to @detiam
