### ISSUE TITLE
Chicken Invaders game doesnt work

### ISSUE THREAD

**Issue by iceman-twitch** [alex47exe/gse_fork#8]
I can see the lobby I created on the other PC but I cannot join at all.
Tried lobby connect exe aswell. Experimental dll and the regual too. Nothing changed.
I was trying with Chicken Invaders 5.

**Comment by alex47exe** [comment]
I'm not maintaining/improving the emulator, only the generate_emu_config for it. Please mention the issue on Detanup01's gbe_fork.
